M48
; DRILL file {KiCad (6.0.4-0)} date 2022 April 11, Monday 20:23:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-11T20:23:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X121.768Y-62.535
X121.92Y-129.0
X168.0Y-129.0
X168.834Y-63.0
T0
M30
